export const NOTIFICATION_TYPES = {
  BASIC: "BASIC"
};

export const USER_ROLES = {
  VENDOR_ACCOUNT_OWNER: "VENDOR_ACCOUNT_OWNER",
  VENDOR_ADMIN: "VENDOR_ADMIN",
  VENDOR_EMPLOYEE: "VENDOR_EMPLOYEE"
};
