export default {
  REWARDING_POINTS_TO_CUSTOMER_ERROR: "REWARDING_POINTS_TO_CUSTOMER_ERROR",
  REDEEMING_CUSTOMER_REWARD_POINTS_ERROR:
    "REDEEMING_CUSTOMER_REWARD_POINTS_ERROR",
  FETCHING_CUSTOMER_REWARD_DETAILS_ERROR:
    "FETCHING_CUSTOMER_REWARD_DETAILS_ERROR",
  FETCHING_CUSTOMER_DEAL_DETAILS_ERROR: "FETCHING_CUSTOMER_DEAL_DETAILS_ERROR",
  FETCHING_CUSTOMER_DETAILS_ERROR: "FETCHING_CUSTOMER_DETAILS_ERROR",
  LOGIN_EMPLOYEE_ERROR: "LOGIN_EMPLOYEE_ERROR",
  SIGNUP_EMPLOYEE_ERROR: "SIGNUP_EMPLOYEE_ERROR",
  APP_INITIALIZATION_ERROR: "APP_INITIALIZATION_ERROR",
  FETCHING_MY_DEALS_ERROR: "FETCHING_MY_DEALS_ERROR",
  FETCHING_ORG_REWARDS_ERROR: "FETCHING_ORG_REWARDS_ERROR",
  CREATING_NEW_DEAL_ERROR: "CREATING_NEW_DEAL_ERROR",
  CREATING_NEW_LOYALTY_REWARD_ERROR: "CREATING_NEW_LOYALTY_REWARD_ERROR",
  FETCHING_MY_ORG_ERROR: "FETCHING_MY_ORG_ERROR",
  FETCHING_ORG_EMPLOYEES_ERROR: "FETCHING_ORG_EMPLOYEES_ERROR",
  UPDATING_EMPLOYEE_ERROR: "UPDATING_EMPLOYEE_ERROR"
};
