export default {
  REWARDING_POINTS_TO_CUSTOMER_ERROR: "REWARDING_POINTS_TO_CUSTOMER_ERROR",
  REDEEMING_CUSTOMER_REWARD_POINTS_ERROR:
    "REDEEMING_CUSTOMER_REWARD_POINTS_ERROR",
  FETCHING_CUSTOMER_REWARD_DETAILS_ERROR:
    "FETCHING_CUSTOMER_REWARD_DETAILS_ERROR",
  FETCHING_CUSTOMER_DEAL_DETAILS_ERROR: "FETCHING_CUSTOMER_DEAL_DETAILS_ERROR",
  FETCHING_CUSTOMER_DETAILS_ERROR: "FETCHING_CUSTOMER_DETAILS_ERROR"
};
