export default {
  INITIALIZING_APP: "INITIALIZING_APP",
  REWARDING_POINTS_TO_CUSTOMER: "REWARDING_POINTS_TO_CUSTOMER",
  REDEEMING_CUSTOMER_REWARD_POINTS: "REDEEMING_CUSTOMER_REWARD_POINTS",
  FETCHING_CUSTOMER_REWARD_DETAILS: "FETCHING_CUSTOMER_REWARD_DETAILS",
  FETCHING_CUSTOMER_DEAL_DETAILS: "FETCHING_CUSTOMER_DEAL_DETAILS",
  FETCHING_CUSTOMER_DETAILS: "FETCHING_CUSTOMER_DETAILS"
};
